# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: Optional[
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
    ] = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: Optional[int] = Field(
        20,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: Optional[int] = Field(
        0,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class ConfigureBaseMaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: Optional[
        List[
            Union[
                BaseMaps,
                BaseMaps1,
                BaseMaps2,
                BaseMaps3,
                BaseMaps4,
                BaseMaps5,
                BaseMaps6,
            ]
        ]
    ] = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
                "max_zoom": 20,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
                "max_zoom": 20,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class GetEventsData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_types: List[str] = Field(
        ...,
        description="Specify the event type(s) to analyze (optional). Leave this section empty to analyze all event types.",
        title="Event Types",
    )


class SubjectGroupVar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(..., title="")


class StatusEnum(str, Enum):
    active = "active"
    overdue = "overdue"
    done = "done"
    cancelled = "cancelled"


class VehiclePatrols(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    patrol_types: List[str] = Field(
        ...,
        description="Specify the patrol type(s) to analyze (optional). Leave empty to analyze all patrol types.",
        title="Patrol Types",
    )
    status: Optional[List[StatusEnum]] = Field(
        ["done"],
        description="Choose to analyze patrols with a certain status. If left empty, patrols of all status will be analyzed",
        title="Patrol Status",
    )


class FootPatrols(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    patrol_types: List[str] = Field(
        ...,
        description="Specify the patrol type(s) to analyze (optional). Leave empty to analyze all patrol types.",
        title="Patrol Types",
    )
    status: Optional[List[StatusEnum]] = Field(
        ["done"],
        description="Choose to analyze patrols with a certain status. If left empty, patrols of all status will be analyzed",
        title="Patrol Status",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define analysis time range",
    )
    configure_base_maps: Optional[ConfigureBaseMaps] = Field(
        None, title="Configure base map layers"
    )
    er_client_name: Optional[ErClientName] = Field(
        None, title="Connect to earth ranger"
    )
    get_events_data: Optional[GetEventsData] = Field(None, title="Retrieve all events")
    subject_group_var: Optional[SubjectGroupVar] = Field(None, title="")
    vehicle_patrols: Optional[VehiclePatrols] = Field(
        None, title="Retrieve vehicle patrols"
    )
    foot_patrols: Optional[FootPatrols] = Field(None, title="Retrieve foot patrols")
