# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map_1
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    compute_view_state_from_gdf as compute_view_state_from_gdf,
)

get_subjectgroup_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_ext_ste.tasks.filter import (
    flexible_previous_period as flexible_previous_period,
)

get_subjectgroup_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.config import prefix_string_var as prefix_string_var
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.skip import (
    any_keyed_iterables_are_skips as any_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_path_layer as create_path_layer_1,
)
from ecoscope_workflows_ext_mep.tasks.results import compile_sitrep as compile_sitrep
from ecoscope_workflows_ext_mep.tasks.results import (
    get_sitrep_event_config as get_sitrep_event_config,
)
from ecoscope_workflows_ext_mep.tasks.results import (
    plot_historic_voltage as plot_historic_voltage,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    column_first_unique_value as column_first_unique_value,
)
from ecoscope_workflows_ext_ste.tasks.transformation import safe_string as safe_string
from ecoscope_workflows_ext_ste.tasks.transformation import (
    subset_columns as subset_columns,
)

get_patrol_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_patrol_observations",  # 🧪
)  # 🧪

get_patrol_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_patrol_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_ext_mep.tasks.reporting import (
    create_mep_monthly_report as create_mep_monthly_report,
)
from ecoscope_workflows_ext_ste.tasks.io import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks.reporting import (
    create_context_page as create_context_page,
)
from ecoscope_workflows_ext_ste.tasks.reporting import (
    prepare_cover_metadata as prepare_cover_metadata,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[{"index_name": "name"}], **(params.get("groupers") or {}))
        .call()
    )

    configure_base_maps = (
        task(set_base_maps_pydeck)
        .validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("configure_base_maps") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    get_events_data = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
            ],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            force_point_geometry=True,
            **(params.get("get_events_data") or {}),
        )
        .call()
    )

    normalize_event_details = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=get_events_data,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_event_details") or {}),
        )
        .call()
    )

    persist_events_csv = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_events_csv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="events",
            df=normalize_event_details,
            **(params.get("persist_events_csv") or {}),
        )
        .call()
    )

    apply_event_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("apply_event_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_event_details,
            input_column_name="event_type",
            output_column_name="event_type_colors",
            colormap="tab20",
            **(params.get("apply_event_colormap") or {}),
        )
        .call()
    )

    generate_ev_layers = (
        task(create_scatterplot_layer_1)
        .validate()
        .set_task_instance_id("generate_ev_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_fill_color": "event_type_colors",
                "get_line_color": "event_type_colors",
                "get_line_width": 0.55,
                "get_radius": 3.55,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Legend",
                "label_column": "event_type",
                "color_column": "event_type_colors",
                "sort": None,
                "label_suffix": None,
            },
            geodataframe=apply_event_colormap,
            **(params.get("generate_ev_layers") or {}),
        )
        .call()
    )

    events_image_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("events_image_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            max_zoom=15,
            gdf=apply_event_colormap,
            **(params.get("events_image_extent") or {}),
        )
        .call()
    )

    draw_sightings_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_sightings_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=generate_ev_layers,
            view_state=events_image_extent,
            **(params.get("draw_sightings_map") or {}),
        )
        .call()
    )

    persist_sightings_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_sightings_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_sightings_map,
            filename="elephant_sightings_map.html",
            filename_suffix=None,
            **(params.get("persist_sightings_urls") or {}),
        )
        .call()
    )

    subject_group_var = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("subject_group_var")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("subject_group_var") or {}))
        .call()
    )

    subject_observations = (
        task(get_subjectgroup_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client_name,
            time_range=time_range,
            subject_group_name=subject_group_var,
            raise_on_empty=False,
            include_details=True,
            include_subjectsource_details=True,
            **(params.get("subject_observations") or {}),
        )
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    convert_relocs_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_relocs_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_observations,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_relocs_timezone") or {}),
        )
        .call()
    )

    subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=subject_observations,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__hex",
                "extra__subject__sex",
                "extra__created_at",
                "extra__subject__subject_subtype",
                "extra__subjectsource__id",
                "extra__subjectsource__assigned_range",
                "extra__observation_details",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("subject_reloc") or {}),
        )
        .call()
    )

    set_previous_period = (
        task(flexible_previous_period)
        .validate()
        .set_task_instance_id("set_previous_period")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(timerange=time_range, **(params.get("set_previous_period") or {}))
        .call()
    )

    previous_subject_observations = (
        task(get_subjectgroup_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("previous_subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client_name,
            time_range=set_previous_period,
            subject_group_name=subject_group_var,
            raise_on_empty=False,
            include_details=True,
            include_subjectsource_details=True,
            **(params.get("previous_subject_observations") or {}),
        )
        .call()
    )

    convert_prev_relocs_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_prev_relocs_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=previous_subject_observations,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_prev_relocs_timezone") or {}),
        )
        .call()
    )

    previous_subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("previous_subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_prev_relocs_timezone,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__hex",
                "extra__subject__sex",
                "extra__created_at",
                "extra__subject__subject_subtype",
                "extra__subjectsource__id",
                "extra__subjectsource__assigned_range",
                "extra__observation_details",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("previous_subject_reloc") or {}),
        )
        .call()
    )

    sort_curr_relocs = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_curr_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_reloc,
            column_name="fixtime",
            ascending=True,
            na_position="last",
            **(params.get("sort_curr_relocs") or {}),
        )
        .call()
    )

    persist_relocs_geoparquet = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_relocs_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sort_curr_relocs,
            filetype="geoparquet",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="relocations",
            **(params.get("persist_relocs_geoparquet") or {}),
        )
        .call()
    )

    sort_prev_relocs = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_prev_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=previous_subject_reloc,
            column_name="fixtime",
            ascending=True,
            na_position="last",
            **(params.get("sort_prev_relocs") or {}),
        )
        .call()
    )

    persist_prev_relocs_geoparquet = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_prev_relocs_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sort_prev_relocs,
            filetype="geoparquet",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="previous_period_relocations",
            **(params.get("persist_prev_relocs_geoparquet") or {}),
        )
        .call()
    )

    extract_current_voltage = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_current_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sort_curr_relocs,
            column_name="observation_details",
            field_name_options=["battery", "mainVoltage", "batt", "power"],
            output_type="float",
            output_column_name="voltage",
            **(params.get("extract_current_voltage") or {}),
        )
        .call()
    )

    extract_previous_voltage = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_previous_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sort_prev_relocs,
            column_name="observation_details",
            field_name_options=["battery", "mainVoltage", "batt", "power"],
            output_type="float",
            output_column_name="voltage",
            **(params.get("extract_previous_voltage") or {}),
        )
        .call()
    )

    split_current_relocs = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_current_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_current_voltage,
            groupers=groupers,
            **(params.get("split_current_relocs") or {}),
        )
        .call()
    )

    split_previous_relocs = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_previous_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_previous_voltage,
            groupers=groupers,
            **(params.get("split_previous_relocs") or {}),
        )
        .call()
    )

    unique_subject_name = (
        task(column_first_unique_value)
        .validate()
        .set_task_instance_id("unique_subject_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="name", **(params.get("unique_subject_name") or {}))
        .mapvalues(argnames=["df"], argvalues=split_current_relocs)
    )

    safe_subject_name = (
        task(safe_string)
        .validate()
        .set_task_instance_id("safe_subject_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("safe_subject_name") or {}))
        .mapvalues(argnames=["value"], argvalues=unique_subject_name)
    )

    voltage_filename = (
        task(prefix_string_var)
        .validate()
        .set_task_instance_id("voltage_filename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="_historic_voltage.html", **(params.get("voltage_filename") or {}))
        .mapvalues(argnames=["prefix"], argvalues=safe_subject_name)
    )

    zip_current_prev_name = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_current_prev_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[split_current_relocs, split_previous_relocs],
            **(params.get("zip_current_prev_name") or {}),
        )
        .call()
    )

    draw_historic_voltage = (
        task(plot_historic_voltage)
        .validate()
        .set_task_instance_id("draw_historic_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column="voltage", **(params.get("draw_historic_voltage") or {}))
        .mapvalues(
            argnames=["current_relocs", "previous_relocs"],
            argvalues=zip_current_prev_name,
        )
    )

    historic_voltage_text = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("historic_voltage_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[voltage_filename, draw_historic_voltage],
            **(params.get("historic_voltage_text") or {}),
        )
        .call()
    )

    persist_collar_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_collar_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix=None,
            **(params.get("persist_collar_html") or {}),
        )
        .mapvalues(argnames=["filename", "text"], argvalues=historic_voltage_text)
    )

    collared_voltage_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("collared_voltage_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Collar Voltage", **(params.get("collared_voltage_widget") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_collar_html)
    )

    grouped_collared_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_collared_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=collared_voltage_widget,
            **(params.get("grouped_collared_widget") or {}),
        )
        .call()
    )

    convert_collar_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_collar_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_collar_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_collar_html)
    )

    convert_to_trajectories = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("convert_to_trajectories")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=sort_curr_relocs,
            trajectory_segment_filter={
                "min_length_meters": 0.001,
                "max_length_meters": 5000,
                "min_time_secs": 1,
                "max_time_secs": 21600,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 9,
            },
            **(params.get("convert_to_trajectories") or {}),
        )
        .call()
    )

    add_temporal_index_to_traj = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("add_temporal_index_to_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_to_trajectories,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("add_temporal_index_to_traj") or {}),
        )
        .call()
    )

    classify_trajectories_speed_bins = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("classify_trajectories_speed_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_temporal_index_to_traj,
            input_column_name="speed_kmhr",
            output_column_name="speed_bins",
            classification_options={"scheme": "equal_interval", "k": 6},
            label_options={
                "label_ranges": True,
                "label_decimals": 1,
                "label_suffix": " km/h",
            },
            **(params.get("classify_trajectories_speed_bins") or {}),
        )
        .call()
    )

    sort_trajs_by_speed = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_trajs_by_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="speed_bins",
            na_position="first",
            ascending=True,
            df=classify_trajectories_speed_bins,
            **(params.get("sort_trajs_by_speed") or {}),
        )
        .call()
    )

    apply_speed_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("apply_speed_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="speed_bins",
            output_column_name="speed_bins_colormap",
            colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
            df=sort_trajs_by_speed,
            **(params.get("apply_speed_colormap") or {}),
        )
        .call()
    )

    filter_speed_cols = (
        task(subset_columns)
        .validate()
        .set_task_instance_id("filter_speed_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=[
                "dist_meters",
                "speed_bins_colormap",
                "geometry",
                "speed_kmhr",
                "speed_bins",
            ],
            exclude=None,
            strict=False,
            df=apply_speed_colormap,
            **(params.get("filter_speed_cols") or {}),
        )
        .call()
    )

    generate_speedmap_layers = (
        task(create_path_layer_1)
        .validate()
        .set_task_instance_id("generate_speedmap_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_color": "speed_bins_colormap",
                "get_width": 2.85,
                "width_scale": 1,
                "width_min_pixels": 2,
                "width_max_pixels": 8,
                "width_units": "pixels",
                "cap_rounded": True,
                "joint_rounded": True,
                "billboard": False,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Speed (km/h)",
                "label_column": "speed_bins",
                "color_column": "speed_bins_colormap",
                "sort": "ascending",
                "label_suffix": None,
            },
            geodataframe=filter_speed_cols,
            **(params.get("generate_speedmap_layers") or {}),
        )
        .call()
    )

    speed_image_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("speed_image_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            max_zoom=15,
            gdf=filter_speed_cols,
            **(params.get("speed_image_extent") or {}),
        )
        .call()
    )

    draw_speedmap = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_speedmap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=generate_speedmap_layers,
            view_state=speed_image_extent,
            **(params.get("draw_speedmap") or {}),
        )
        .call()
    )

    persist_speedmap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_speedmap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix=None,
            filename="elephant_speedmap.html",
            text=draw_speedmap,
            **(params.get("persist_speedmap_html") or {}),
        )
        .call()
    )

    get_sitrep_config = (
        task(get_sitrep_event_config)
        .validate()
        .set_task_instance_id("get_sitrep_config")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(region_column="region", **(params.get("get_sitrep_config") or {}))
        .call()
    )

    generate_sitrep_df = (
        task(compile_sitrep)
        .validate()
        .set_task_instance_id("generate_sitrep_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            er_io=er_client_name,
            event_details=get_sitrep_config,
            time_range=time_range,
            **(params.get("generate_sitrep_df") or {}),
        )
        .call()
    )

    persist_sitrep_csv = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_sitrep_csv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="sitrep_report",
            df=generate_sitrep_df,
            **(params.get("persist_sitrep_csv") or {}),
        )
        .call()
    )

    vehicle_patrols = (
        task(get_patrol_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("vehicle_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            **(params.get("vehicle_patrols") or {}),
        )
        .call()
    )

    vehicle_patrol_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("vehicle_patrol_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=vehicle_patrols,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "geometry",
                "patrol_type__value",
                "patrol_type__display",
                "patrol_serial_number",
                "patrol_status",
                "patrol_subject",
                "groupby_col",
                "fixtime",
                "junk_status",
                "extra__source",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("vehicle_patrol_reloc") or {}),
        )
        .call()
    )

    vehicle_patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("vehicle_patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=vehicle_patrol_reloc,
            trajectory_segment_filter={
                "min_length_meters": 0.35,
                "max_length_meters": 5000.0,
                "max_time_secs": 18000.0,
                "min_time_secs": 1.0,
                "max_speed_kmhr": 100.0,
                "min_speed_kmhr": 10.0,
            },
            **(params.get("vehicle_patrol_traj") or {}),
        )
        .call()
    )

    persist_vehicle_traj = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_vehicle_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=vehicle_patrol_traj,
            filetype="geoparquet",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="vehicle_patrol_trajectories",
            **(params.get("persist_vehicle_traj") or {}),
        )
        .call()
    )

    vehicle_traj_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("vehicle_traj_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=vehicle_patrol_traj,
            colormap="viridis",
            input_column_name="extra__patrol_type__value",
            output_column_name="patrol_type_colormap",
            **(params.get("vehicle_traj_colormap") or {}),
        )
        .call()
    )

    vehicle_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("vehicle_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            max_zoom=15,
            gdf=vehicle_traj_colormap,
            **(params.get("vehicle_extent") or {}),
        )
        .call()
    )

    vehicle_patrol_path_layer = (
        task(create_path_layer_1)
        .validate()
        .set_task_instance_id("vehicle_patrol_path_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_color": "patrol_type_colormap",
                "get_width": 2.85,
                "width_scale": 1,
                "width_min_pixels": 2,
                "width_max_pixels": 8,
                "width_units": "pixels",
                "cap_rounded": True,
                "joint_rounded": True,
                "billboard": False,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Patrol team",
                "label_column": "extra__patrol_type__value",
                "color_column": "patrol_type_colormap",
                "sort": "ascending",
                "label_suffix": None,
            },
            geodataframe=vehicle_traj_colormap,
            **(params.get("vehicle_patrol_path_layer") or {}),
        )
        .call()
    )

    draw_vehicles_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_vehicles_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=vehicle_patrol_path_layer,
            view_state=vehicle_extent,
            **(params.get("draw_vehicles_map") or {}),
        )
        .call()
    )

    vehicle_patrol_map = (
        task(persist_text)
        .validate()
        .set_task_instance_id("vehicle_patrol_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="vehicle_patrols_map.html",
            filename_suffix=None,
            text=draw_vehicles_map,
            **(params.get("vehicle_patrol_map") or {}),
        )
        .call()
    )

    foot_patrols = (
        task(get_patrol_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("foot_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            **(params.get("foot_patrols") or {}),
        )
        .call()
    )

    foot_patrol_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("foot_patrol_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=foot_patrols,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "geometry",
                "patrol_type__value",
                "patrol_type__display",
                "patrol_serial_number",
                "patrol_status",
                "patrol_subject",
                "groupby_col",
                "fixtime",
                "junk_status",
                "extra__source",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("foot_patrol_reloc") or {}),
        )
        .call()
    )

    foot_patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("foot_patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=foot_patrol_reloc,
            trajectory_segment_filter={
                "min_length_meters": 0.001,
                "max_length_meters": 5000.0,
                "max_time_secs": 14400.0,
                "min_time_secs": 1.0,
                "max_speed_kmhr": 9.0,
                "min_speed_kmhr": 0.5,
            },
            **(params.get("foot_patrol_traj") or {}),
        )
        .call()
    )

    persist_foot_traj = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_foot_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=foot_patrol_traj,
            filetype="geoparquet",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="foot_patrol_trajectories",
            **(params.get("persist_foot_traj") or {}),
        )
        .call()
    )

    foot_traj_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("foot_traj_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=foot_patrol_traj,
            colormap="viridis",
            input_column_name="extra__patrol_type__value",
            output_column_name="patrol_type_colormap",
            **(params.get("foot_traj_colormap") or {}),
        )
        .call()
    )

    foot_image_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("foot_image_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            max_zoom=15,
            gdf=foot_traj_colormap,
            **(params.get("foot_image_extent") or {}),
        )
        .call()
    )

    foot_patrol_path_layer = (
        task(create_path_layer_1)
        .validate()
        .set_task_instance_id("foot_patrol_path_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_color": "patrol_type_colormap",
                "get_width": 2.85,
                "width_scale": 1,
                "width_min_pixels": 2,
                "width_max_pixels": 8,
                "width_units": "pixels",
                "cap_rounded": True,
                "joint_rounded": True,
                "billboard": False,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Patrol team",
                "label_column": "extra__patrol_type__value",
                "color_column": "patrol_type_colormap",
                "sort": "ascending",
                "label_suffix": None,
            },
            geodataframe=foot_traj_colormap,
            **(params.get("foot_patrol_path_layer") or {}),
        )
        .call()
    )

    draw_foot_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_foot_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=foot_patrol_path_layer,
            view_state=foot_image_extent,
            **(params.get("draw_foot_map") or {}),
        )
        .call()
    )

    foot_patrol_map = (
        task(persist_text)
        .validate()
        .set_task_instance_id("foot_patrol_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="foot_patrols_map.html",
            filename_suffix=None,
            text=draw_foot_map,
            **(params.get("foot_patrol_map") or {}),
        )
        .call()
    )

    convert_sightings_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_sightings_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_sightings_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_sightings_png") or {}),
        )
        .call()
    )

    convert_speedmap_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_speedmap_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_speedmap_html,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_speedmap_png") or {}),
        )
        .call()
    )

    convert_vehicle_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_vehicle_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=vehicle_patrol_map,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_vehicle_png") or {}),
        )
        .call()
    )

    convert_foot_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_foot_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=foot_patrol_map,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_foot_png") or {}),
        )
        .call()
    )

    download_cover_page = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("download_cover_page")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/95fux8w00h9u4wg2sufij/mep_monthly_report.docx?rlkey=nbibg8ulnlz0w4q53jw2db6y3&st=6own6h01&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("download_cover_page") or {}),
        )
        .call()
    )

    download_content_page = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("download_content_page")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/1u7d68pr8hvc27gf2ns85/mep_monthly_indv_report.docx?rlkey=wss0x8sa9i5fgl9yjco7paa03&st=b8fsdnxg&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("download_content_page") or {}),
        )
        .call()
    )

    download_logo = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("download_logo")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/se63iljd7h9zdi4szv2pt/MEP-logo-dark-linear.png?rlkey=usqs76f4ejd2nyqrpmwxmks0o&st=0z2jfaif&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            unzip=False,
            retries=2,
            **(params.get("download_logo") or {}),
        )
        .call()
    )

    cover_page_context = (
        task(prepare_cover_metadata)
        .validate()
        .set_task_instance_id("cover_page_context")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            org_logo_path=download_logo,
            report_period=time_range,
            prepared_by="Ecoscope",
            extra_fields=None,
            time_generated_format="%Y-%m-%d %H:%M:%S",
            **(params.get("cover_page_context") or {}),
        )
        .call()
    )

    persist_cover_page = (
        task(create_context_page)
        .validate()
        .set_task_instance_id("persist_cover_page")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            template_path=download_cover_page,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            context=cover_page_context,
            filename="mep_monthly_cover_page.docx",
            **(params.get("persist_cover_page") or {}),
        )
        .call()
    )

    create_monthly_report = (
        task(create_mep_monthly_report)
        .validate()
        .set_task_instance_id("create_monthly_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            template_path=download_content_page,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="overall_report.docx",
            **(params.get("create_monthly_report") or {}),
        )
        .call()
    )

    sightings_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("sightings_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Elephant Sightings Map",
            data=persist_sightings_urls,
            **(params.get("sightings_map_widget") or {}),
        )
        .call()
    )

    speedmap_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("speedmap_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Speed Map",
            data=persist_speedmap_html,
            **(params.get("speedmap_widget") or {}),
        )
        .call()
    )

    vehicle_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("vehicle_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Vehicle Patrols Map",
            data=vehicle_patrol_map,
            **(params.get("vehicle_map_widget") or {}),
        )
        .call()
    )

    foot_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("foot_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Foot Patrols Map",
            data=foot_patrol_map,
            **(params.get("foot_map_widget") or {}),
        )
        .call()
    )

    draw_sitrep_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("draw_sitrep_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=generate_sitrep_df,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Sitrep Report",
            **(params.get("draw_sitrep_table") or {}),
        )
        .call()
    )

    persist_sitrep_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_sitrep_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_sitrep_table,
            filename="sitrep_report_table.html",
            filename_suffix=None,
            **(params.get("persist_sitrep_table_html") or {}),
        )
        .call()
    )

    sitrep_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("sitrep_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Sitrep Report",
            data=persist_sitrep_table_html,
            **(params.get("sitrep_table_widget") or {}),
        )
        .call()
    )

    mep_monthly_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("mep_monthly_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                grouped_collared_widget,
                sightings_map_widget,
                speedmap_widget,
                vehicle_map_widget,
                foot_map_widget,
                sitrep_table_widget,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("mep_monthly_dashboard") or {}),
        )
        .call()
    )

    return mep_monthly_dashboard
